import type { Metadata } from "next";
import { Barlow, DM_Sans, Fraunces, Roboto, Sora } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
	variable: "--font-roboto",
	weight: ["700", "400"],
});

const sora = Sora({
	variable: "--font-sora",
	weight: ["700", "400", "600", "500"],
});

const barlow = Barlow({
	variable: "--font-barlow",
	weight: ["600"],
});

const fraunces = Fraunces({
	variable: "--font-fraunces",
	weight: ["700", "900"],
});

const dmSans = DM_Sans({
	variable: "--font-dm-sans",
	subsets: ["latin"],
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${roboto.variable} ${sora.variable} ${barlow.variable} ${fraunces.variable} ${dmSans.variable} antialiased`}
			>
				{/* <CustomCursor /> */}
				{children}
			</body>
		</html>
	);
}
