import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Sora } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const roboto = Roboto({
	variable: "--font-roboto",
	weight: ["700", "400"],
});

const sora = Sora({
	variable: "--font-sora",
	weight: ["700", "400", "600", "500"],
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${sora.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
